export const UPDATE_USER = "UPDATE_USER"

export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_ALL_CART_ITEMS = "REMOVE_ALL_CART_ITEMS"
export const REMOVE_ONE_CART_ITEM = "REMOVE_ONE_CART_ITEM"
export const CHANGE_CART_ITEM_VALUE = "CHANGE_CART_ITEM_VALUE"